parameters:
#    mall_core.example.class: Mall\Bundle\CoreBundle\Example

services:
#    mall_core.example:
#        class: %mall_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
