parameters:
#    mall_web_frontend.example.class: Mall\Web\FrontendBundle\Example

services:
#    mall_web_frontend.example:
#        class: %mall_web_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
